version: '3.3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: dev
    volumes:
      - ..:/home/user/cbase:rw
      - ~/.ssh:/home/user/.ssh:rw
    command: sleep infinity