version: '3.3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: dev
    volumes:
      - ..:/home/user/cbase:rw
      - ~/.ssh/id_rsa:/home/user/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/home/user/.ssh/id_rsa.pub:ro
      - ~/.gnupg:/home/user/.gnupg:rw
    command: sleep infinity