version: '3.3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/cbase:rw
      - ~/.ssh:/home/dev/.ssh:ro
    command: sleep infinity
