name: Docker Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tear down Docker Compose
        run: |
          docker-compose -f .devcontainer/docker-compose.yml down

      - name: Set up Docker Compose
        run: |
          docker-compose -f .devcontainer/docker-compose.yml up -d

      - name: Run tests
        run: |
          docker-compose -f .devcontainer/docker-compose.yml exec -T devcontainer bash -c "cd /workspaces/cbase && make coverage"

      - name: Tear down Docker Compose
        run: |
          docker-compose -f .devcontainer/docker-compose.yml down

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: coverage

      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v4