name: Docker Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and run dev container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          make test
          bin/test
