name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  check:
    uses: ./.github/workflows/check.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml

  report:
    uses: ./.github/workflows/report.yml
