name: Report

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y valgrind gcovr

      - name: Make Report
        run: |
          make report

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
