name: upterm

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1